### ISSUE TITLE
Upload BASE CNES 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#175]
**Description**: Efetuar o **UPLOAD** da **Base CNES** para que as salas de vacina sejam carregadas automaticamente para os Municípios.

**Regra de Negócio:**

- Utilizaremos a Planilha tbEstabelecimento202212.csv como BASE. 

- Para a planilha base, utilizaremos somente as colunas listadas abaixo:

**Obs: Ignorar toda e qualquer coluna que **não** esteja presente na listagem abaixo**

CO_UNIDADE
CO_CNES
NO_FANTASIA
NO_LOGRADOURO
NU_ENDERECO
NO_COMPLEMENTO
NO_BAIRRO
NU_TELEFONE
NU_LATITUDE
NU_LONGITUDE
CO_MUNICIPIO_GESTOR*
CO_ESTADO_GESTOR*
CO_TIPO_UNIDADE
CO_TIPO_ESTABELECIMENTO

- A coluna **CO_TIPO_UNIDADE**, está vinculada a planilha **"tbTipoUnidade202212.csv"** e deve conter apenas  os seguintes códigos (71,72,1,2,4,22,40,42,32,36,43,61,62,15,20,21,5,7,50,73,74,85,83,77).

- A coluna **CO_TIPO_ESTABELECIMENTO**, está vinculada a planilha **"tbTipoEstabelecimento202212.csv"** e deve conter apenas  os seguintes códigos (1,6,8,9,13,14,16,23,25) 

- A coluna **CO_ESTADO_GESTOR**, está vinculada a planilha **"tbEstado202212.csv"**.

- A coluna **CO_MUNICIPIO_GESTOR**, está vinculada a planilha **"tbMunicipio202212.csv"**

**Objetivo/ Resultado Esperado:** 

- Garantir que o Município esteja com as salas de vacina carregadas ao entrar na tela de territórios

[Link](https://xd.adobe.com/view/343271d4-6e28-4037-b01e-e3a977449d3b-6161/screen/e9f0e9d6-b7d1-48db-8f6d-54e1c8a1bdc9)

**Links para Download:**

tbEstabelecimento -> [Link](https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/ERfKDM8fivFAlWPcG40FjBYBUTHx7U_vS4RreMuiWV6HNA)

tbEstado202212 -> [Link](https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/EamP_LuK8bZDgF2yhhb2sq8Bq1vKh6OlGCNeHaesB-sbrw)

tbMunicipio202212 -> [Link](https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/EYXkcsDmX8pLrdwE-Ru1XMkBY_d0LUt_be8M_bBOPsqH4Q)

tbTipoEstabelecimento202212 -> [Link](https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/EShqLJRUQBNKt9DeV8sBEg4BrhjEBzLJWyaIqIzv3dv3Wg)

tbTipoUnidade202212 -> [Link](https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/EVcCvZntbDdClBo5-Zp9kBABFLP63ZMuVBRiCTs9BALUvg)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [ ] Deve seguir a regra de negócio estabelecida.

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo.

- [ ] Deve atingir o objetivo/resultado esperado.

- [ ] Deve ser feito o deploy em ambiente de Homologacão.

- [ ] Deve passar por aprovacão do time de UX/UI Design.
