### ISSUE TITLE
Painel Nacional

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#243]
Link protótipo: https://xd.adobe.com/view/c87ed8ab-fbd3-415f-8f70-95713b6bfcdf-9d2d/ 

**O que não entra:**

- Filtro de participantes do SELO

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

**Comment by lucasferreiraunicef** [comment]
@dlazaroni

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.
