### ISSUE TITLE
Painel Município

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#244]
**Link protótipo:** https://xd.adobe.com/view/c87ed8ab-fbd3-415f-8f70-95713b6bfcdf-9d2d/screen/09f9fbce-45f4-4ff0-b72b-84becdfdac7a

**Itens Desconsiderados:**

- "Casos encerrados sem conclusão"
- "Lembretes futuros de 30 e 60 dias"

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

**Comment by lucasferreiraunicef** [comment]
@dlazaroni

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.

**Comment by rodrigoluzlopes** [comment]
Painel nacional é diferente de home.
Apenas para o gestor nacional, a home será o painel

**Comment by rodrigoluzlopes** [comment]
INSERT INTO bav.menus
(id, uuid, name, created_at, updated_at)
VALUES(12, 'da5c53c8-1493-4e33-8bfa-423e6032d2b4', 'painel', '2024-07-16 15:26:12', '2024-07-16 15:26:12');
