### ISSUE TITLE
Listagem de Análises Pendentes

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#374]
Description: Alterar a estrutura inserindo um filtro.

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [] Conter a jornada de usuário completa.

 

- [] Todas as validações de campo devem estar funcionando.

 

- [] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [] Deve ser aceito e aprovado em homologação.

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
